image: gradle:4.0-jdk8

stages:
  - build
  - test

before_script:
  - gradle -version

build:
  stage: build
  script:
    - gradle clean build -x test

test:
  stage: test
  script:
    - gradle clean test